spring.application.name=ecom-application
server.port=8082
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:f78464ea-ac5d-4196-b1f0-9e9f017c6b90
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true